WIDTH = 800
HEIGHT = 520
SIZE = (WIDTH, HEIGHT)

STEP = 10

TIME_DELAY = 100  # ms

FOOD_WIDTH = 10
FOOD_HEIGHT = 10

BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

SNAKE_COLOR = RED
FOOD_COLOR = GREEN
LABEL_COLOR = YELLOW

FONT = "monospace"
FONT_SIZE = 25
FONT_COORDINATES = (10, 10)

GAME_OVER_FONT_SIZE = 44
GAME_OVER_LABEL_X = WIDTH // 10
GAME_OVER_LABEL_Y = 100

PARAMS = ((RED, GAME_OVER_FONT_SIZE + 10, (WIDTH // 3, GAME_OVER_FONT_SIZE)),
          (GREEN, GAME_OVER_FONT_SIZE, (WIDTH // 4, GAME_OVER_FONT_SIZE * 3)),
          (GREEN, GAME_OVER_FONT_SIZE, (WIDTH // 4, GAME_OVER_FONT_SIZE * 4)),
          (YELLOW, GAME_OVER_FONT_SIZE, (WIDTH // 6, GAME_OVER_FONT_SIZE * 7)),
          (RED, 24, (WIDTH // 10, GAME_OVER_FONT_SIZE * 10)))
